name: Auto Get Waydroid Image（ARM64）
run-name: ${{ github.actor }} Auto Get Waydroid Image（ARM64） 🚀
on:
#  schedule:
  push:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get
        env: 
          PASSWORD: ${{ secrets.PASSWORD }}
          USER: ${{ secrets.USER }}
          URL: ${{ secrets.URL }}
        run: |
          sudo apt update
          sudo apt install git -y
          git clone https://github.com/gfdgd-xi/waydroid-deb-build.git
          cd waydroid-deb-build
          bash build-arm64.sh
          
          
          
          
      - name: upload result(system.img)
        uses: actions/upload-artifact@v1
        with:
          name: system.img
          path: /tmp/system.img
      - name: upload result(vendor.img)
        uses: actions/upload-artifact@v1
        with:
          name: vendor.img
          path: /tmp/vendor.img
      - name: upload result(waydroid-android-image-gapps.deb)
        uses: actions/upload-artifact@v1
        with:
          name: waydroid-android-image-gapps.deb
          path: /tmp/waydroid-android-image-gapps.deb
      - name: upload result(waydroid.deb)
        uses: actions/upload-artifact@v1
        with:
          name: waydroid.deb
          path: /tmp/waydroid.deb
            

  

      
    
